name: build-cmake

on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DISPLAY_INSTALL_TIMES: "ON"
  HOMEBREW_NO_ANALYTICS: "ON"
  HOMEBREW_NO_AUTO_UPDATE: "ON"
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
  HOMEBREW_NO_GITHUB_API: "ON"
  HOMEBREW_NO_INSTALL_CLEANUP: "ON"

jobs:
  build-cmake:
    name: ${{ matrix.os }}, gfortran
    strategy:
      fail-fast: false
      matrix:
#        os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages (ubuntu)
        if: contains(matrix.os,'ubuntu')
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc gfortran

#      - name: Install packages (macOS)
#        if: contains(matrix.os,'macos')
#        run: |
#          brew install gcc || brew upgrade gcc || true

      - name: Build
        run: |
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -DCMAKE_Fortran_COMPILER=gfortran
          cmake --build build/ --target all

