name: test-nodata

on: [push, pull_request, workflow_dispatch]

env:
  HOMEBREW_DISPLAY_INSTALL_TIMES: "ON"
  HOMEBREW_NO_ANALYTICS: "ON"
  HOMEBREW_NO_AUTO_UPDATE: "ON"
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
  HOMEBREW_NO_GITHUB_API: "ON"
  HOMEBREW_NO_INSTALL_CLEANUP: "ON"

jobs:
  test-nodata:
    name: ubuntu-latest, gfortran

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages (ubuntu)
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc gfortran numdiff

      - name: Build
        run: |
          cmake -Bbuild -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug -Wno-dev
          cmake --build build/ --target all
          cd build
          ctest -L nodata --output-on-failure
